### ISSUE TITLE
When the app is opened by link, sometimes the last-viewed page is restored instead

### ISSUE THREAD

**Issue by smichel17** [slapperwan/gh4a#1145] opened 2021-11-12 17:41 UTC
**Steps to reproduce:**

1. Open a link to a GitHub issue (let's call it `#1`)
    - Does not matter if the app is previously open, but it must be opened by link (to issue?).
2. Put Octodroid into the background (e.g. go home or switch apps)
     - App must remain running in the background (do not dismiss it from recent apps or close it using the back button)
3. Open a link to a different GitHub issue (`#2`)

**Expected:** App opens to issue `#2`
**Actual:** App just switches back to the previous view of issue `#1`

Easiest to reproduce accidentally if you have email notifications enabled.

I suspect the root cause is some Activity not handling the intent the same in its `onCreate` and `onNewIntent` callbacks.

**Comment by maniac103** [comment] 2021-11-26 11:50
> I suspect the root cause is some Activity not handling the intent the same in its onCreate and onNewIntent callbacks.

The only activity with non-default launch mode is the launcher activity, and with default launch mode one doesn't get `onNewIntent`.
The `BrowseFilter` activity, which does the link handling, just is a proxy, that is, keeps the intent flags it's launched with in the intent it then launches after resolving. That means task behavior depends on the launching app ... which is? ;-)

**Comment by maniac103** [comment] 2021-11-26 11:52
Nvm, I can reproduce with the AOSP email app, Google Keep doesn't reproduce because it doesn't set `FLAG_ACTIVITY_NEW_TASK`.

**Closed** 2021-11-26 12:59 UTC

**Comment by smichel17** [comment] 2021-11-26 16:32
Thanks for the fix :)
