### ISSUE TITLE
[Feature Request] reactions to issue comments

### ISSUE THREAD

**Issue by gregsdennis** [slapperwan/gh4a#573] opened 2017-04-10 20:08 UTC
The GitHub web UI allows reactions (emoji with counts) on comments on issues.  This should be supported in the app.

**Comment by maniac103** [comment] 2017-04-10 20:11
Dupe of #304.

**Closed** 2017-04-10 20:12 UTC

**Comment by gregsdennis** [comment] 2017-04-10 20:17
So it is.  I didn't see it when I browsed through them.  Thanks.
