### ISSUE TITLE
gh4a

### ISSUE THREAD

**Issue by domoaligato** [slapperwan/gh4a#39] opened 2011-08-05 13:57 UTC
i love your app but wanted to make a suggestion. could you add a feature to notify on activity feed changes?

**Comment by JohnVeness** [comment] 2016-10-15 22:17
Can someone edit the title of this issue, for clarity?

**Comment by maniac103** [comment] 2017-03-05 16:34
Dupe of #42 anyway.

**Closed** 2017-03-05 16:35 UTC
Labels: future
