### ISSUE TITLE
Device rotation loosing issue comment

### ISSUE THREAD

**Issue by moltob** [slapperwan/gh4a#694] opened 2017-09-07 16:50 UTC
1. Start commenting a GH issue in octodroid, do not send it
2. Rotate the phone

The comment text is gone since the issue is reloaded.

Great app! Thanks a lot.

**Comment by Tunous** [comment] 2017-09-07 16:56
Duplicate of #358.

**Comment by maniac103** [comment] 2017-09-07 18:48
Hmm, is this really a dupe? #358 is about pressing back, not about rotating the phone. This one sounds like we're not saving and/or restoring state properly.

@moltob Is this with 4.2.0 or some earlier version?

**Comment by Tunous** [comment] 2017-09-07 18:49
Right, my mistake.

**Comment by moltob** [comment] 2017-09-07 19:09
Yes, it says 4.2.0 in the about screen. Running it on a Moto G v1 on Android 5.1. Let me know if you need more information.

**Comment by Tunous** [comment] 2017-09-07 19:27
I think it's duplicate of #616 then.

@moltob Does it work for you in commit comments like here: https://github.com/slapperwan/gh4a/commit/a9b3cfbe42bf582de0747455311db7aab140bf17?

**Comment by moltob** [comment] 2017-09-07 19:31
Yes, it does keep the comment in that screen as expected.

**Comment by Tunous** [comment] 2017-09-07 19:51
Ok, then closing as a duplicate of #616 😉

**Closed** 2017-09-07 19:51 UTC
