### ISSUE TITLE
[GitHub API] Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by p1r473** [slapperwan/gh4a#1006] opened 2020-07-23 23:01 UTC
Got the following email from GitHub, regarding a deprecated API feature Octodroid is using 
```
Hi,

On July 23rd, 2020 at 22:39 (UTC) your personal access token (Octodroid - Google Pixel XL #2) using AndroidDownloadManager/10 (Linux; U; Android 10; Pixel 4 XL Build/QQ1B.200205.002) was used as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/repositories/77243612/releases/assets/22076138

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.

Depending on your API usage, we'll be sending you this email reminder on a monthly basis for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

Thanks,
The GitHub Team
```

**Comment by maniac103** [comment] 2020-07-24 04:30
This is a dupe of #972.

**Closed by maniac103** 2020-07-24 04:30 UTC
