### ISSUE TITLE
Pull requests showing up in issues

### ISSUE THREAD

**Issue by Nxt3** [slapperwan/gh4a#324] opened 2016-05-24 01:17 UTC
When viewing the issues of a repo, it contains pull requests as well.

**Comment by maniac103** [comment] 2016-05-24 04:15
This is a dupe of #277, but if so many people are confused by it, I wonder whether we shouldn't change this behaviour. PRs are as easily accessible as issues from the repo view anyway.
@slapperwan ?

**Comment by slapperwan** [comment] 2016-05-24 04:42
I'm looking at Github mobile web, it doesn't show the PR in issue listing.  I'm OK to exclude PR in issue listing.

**Comment by maniac103** [comment] 2016-05-24 07:00
I played around with this and found one UI issue: where to place the edit FAB when editing a pull request? Currently PR editing is done through the issue activity as well, which doesn't have tabs.

**Comment by maniac103** [comment] 2016-05-24 07:57
Pushed a branch for that in case anyone wants to try: https://github.com/slapperwan/gh4a/tree/separate-issue-and-pull

**Comment by Nxt3** [comment] 2016-05-24 13:32
Sorry for the dupe; OctoDroid doesn't let you search through issues ;)

But yeah--Desktop doesn't show PRs in issues; to me, this almost seems like a bug. I appreciate you looking into it, @maniac103!

**Comment by maniac103** [comment] 2016-05-24 13:34
4.0 _does_ let you search issues ;) And their web site used to behave differently.
But as I said, it's no big deal to change, largest issue is placing the PR edit button.

**Comment by Nxt3** [comment] 2016-05-24 13:36
Oh snap it does? I feel really dumb for not noticing the button, wow. 

Glad it's an easy fix then. :+1:

**Comment by slapperwan** [comment] 2016-05-24 14:59
@maniac103 I've look into the new branch and I think that's the only place for the edit button.  I can't think of any other place to put.

**Comment by maniac103** [comment] 2016-05-25 10:06
@slapperwan Got an even better idea (I think), let me know about your thoughts :)

**Comment by slapperwan** [comment] 2016-05-25 14:49
So it does fit at the tabs there.  I've no comment.  It just looks weird when it is beside the tabs but better then previous design, at least the button placement is consistent with the issue edit button.

**Comment by maniac103** [comment] 2016-05-25 17:07
Yeah, it does look at little weird or at least unfamiliar, but I can't think of a better place. Only think I was pondering was only showing it in the conversation tab, but having the empty space there while looking at the other tabs didn't seem useful either.

**Closed** 2016-05-27 11:24 UTC
