### ISSUE TITLE
Milestone filtration doesn't work for non-English milestones

### ISSUE THREAD

**Issue by rugabarbo** [slapperwan/gh4a#568] opened 2017-04-04 11:02 UTC
I don't see any issues under my milestone filters...

**Comment by maniac103** [comment] 2017-04-04 15:38
Dupe of #428 ... this issue should be fixed in 4.0.5 though, are you using an oder version?

**Comment by rugabarbo** [comment] 2017-04-04 15:43
I'm using 4.0.5
Not sure this is dupe of #428.

**Comment by maniac103** [comment] 2017-04-04 17:20
Hmm, so what exactly are you doing? Some repo -> issue list -> filter by milestone -> select a milestone -> resulting list is empty?

**Comment by rugabarbo** [comment] 2017-04-04 17:37
> Some repo -> issue list -> filter by milestone -> select a milestone -> resulting list is empty?

Yes exactly.

> Not sure this is dupe of #428.

I mean #428 is about comment button... While this issue is about milestone filtration.
So I'm a bit confused.

**Comment by maniac103** [comment] 2017-04-04 17:38
Oops, typo: I meant #528.

**Comment by rugabarbo** [comment] 2017-04-04 17:45
Yes, that's right. #528 is dupe of this issue.

I see that #528 has been fixed in 4.0.5 version. But I have this version installed and there is still a bug. How can I help localize the problem?

**Comment by rugabarbo** [comment] 2017-04-04 20:50
Perhaps it will be useful: I'm watching the filtering bug in the **private** repository.

**Comment by Tunous** [comment] 2017-04-04 21:19
Works for me both in private and public repositories.

**Comment by rugabarbo** [comment] 2017-04-04 21:50
I think I found the source of the problem. For the milestone «English» filtering works fine, but for the milestone «Русский» doesn't (this is Russian language).

**Closed** 2017-04-05 07:27 UTC

**Comment by rugabarbo** [comment] 2017-04-16 20:44
Thank you a lot. Now it works fine (4.0.6)
