### ISSUE TITLE
crash when open forked rep

### ISSUE THREAD

**Issue by WanderMax** [slapperwan/gh4a#1408] opened 2024-10-18 23:38 UTC
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.meisolsson.githubsdk.model.User.login()' on a null object reference
	at com.gh4a.activities.RepositoryActivity.makeIntent(RepositoryActivity.java:56)
	at com.gh4a.activities.RepositoryActivity.makeIntent(RepositoryActivity.java:52)
	at com.gh4a.fragment.EventListFragment.onItemClick(EventListFragment.java:188)
	at com.gh4a.fragment.EventListFragment.onItemClick(EventListFragment.java:88)
	at com.gh4a.adapter.RootAdapter.onClick(RootAdapter.java:271)
	at com.gh4a.adapter.EventAdapter.onClick(EventAdapter.java:118)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28307)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:200)
	at android.os.Looper.loop(Looper.java:286)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by WanderMax** [comment] 2024-10-18 23:40
![Screenshot_20241019-073917259](https://github.com/user-attachments/assets/b9dfbd60-2a57-4c4d-b21c-16666317543d)
show deleted in forked

**Comment by maniac103** [comment] 2024-10-19 05:45
Dupe of #1401

**Closed by maniac103** 2024-10-19 05:45 UTC
