### ISSUE TITLE
[Bug] App crash when trying to open an deleted repositry from news feedpage

### ISSUE THREAD

**Issue by VillagerTom** [slapperwan/gh4a#1409] opened 2024-10-27 11:12 UTC
![超级截屏_20241027_191508.png](https://github.com/user-attachments/assets/04106da8-a7f8-4cd8-81b9-975fff6506cd)

LogCat crash log

```java
FATAL EXCEPTION: main
Process: com.gh4a, PID: 10455
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.meisolsson.githubsdk.model.User.login()' on a null object reference
	at com.gh4a.activities.RepositoryActivity.makeIntent(RepositoryActivity.java:56)
	at com.gh4a.activities.RepositoryActivity.makeIntent(RepositoryActivity.java:52)
	at com.gh4a.fragment.EventListFragment.onItemClick(EventListFragment.java:188)
	at com.gh4a.fragment.EventListFragment.onItemClick(EventListFragment.java:88)
	at com.gh4a.adapter.RootAdapter.onClick(RootAdapter.java:271)
	at com.gh4a.adapter.EventAdapter.onClick(EventAdapter.java:118)
	at android.view.View.performClick(View.java:5646)
	at android.view.View$PerformClick.run(View.java:22498)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6267)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
```

**Comment by maniac103** [comment] 2024-10-27 11:17
Dupe of #1401.

**Closed by maniac103** 2024-10-27 11:17 UTC
