### ISSUE TITLE
Crash if opening PR and scrolling down to end

### ISSUE THREAD

**Issue by qwerty287** [slapperwan/gh4a#1256] opened 2022-11-03 12:05 UTC
If I open https://github.com/TeamNewPipe/NewPipeExtractor/pull/944 and scroll down to the bottom, octodroid crashes.

```
FATAL EXCEPTION: main
Process: com.gh4a, PID: 27162
java.lang.RuntimeException: PARAGRAPH span must start at paragraph boundary (431 follows  )
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:693)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
	at com.gh4a.utils.HtmlUtils$HtmlToSpannedConverter.convert(HtmlUtils.java:383)
	at com.gh4a.utils.HtmlUtils$Html.fromHtml(HtmlUtils.java:264)
	at com.gh4a.utils.HtmlUtils.encode(HtmlUtils.java:238)
	at com.gh4a.utils.HttpImageGetter$ObjectInfo.encode(HttpImageGetter.java:198)
	at com.gh4a.utils.HttpImageGetter$ObjectInfo.bind(HttpImageGetter.java:171)
	at com.gh4a.utils.HttpImageGetter.bind(HttpImageGetter.java:393)
	at com.gh4a.adapter.timeline.CommentViewHolder.bind(CommentViewHolder.java:141)
	at com.gh4a.adapter.timeline.CommentViewHolder.bind(CommentViewHolder.java:36)
	at com.gh4a.adapter.timeline.TimelineItemAdapter.onBindViewHolder(TimelineItemAdapter.java:278)
	at com.gh4a.adapter.timeline.TimelineItemAdapter.onBindViewHolder(TimelineItemAdapter.java:30)
	at com.gh4a.adapter.RootAdapter.onBindViewHolder(RootAdapter.java:234)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

**Comment by Fs00** [comment] 2022-11-03 17:04
Duplicate of #1253

**Closed** 2023-02-18 14:10 UTC
