### ISSUE TITLE
Pure Black theme for amoled display

### ISSUE THREAD

**Issue by anishmittal2020** [slapperwan/gh4a#957] opened 2020-02-19 07:58 UTC
Pure Black theme for amoled display can be useful.

**Comment by smichel17** [comment] 2020-02-19 11:45
Pure black themes can look nice, and I often use them myself, but they're not that useful -- compared to dark gray, the power savings are [not that different](https://www.xda-developers.com/amoled-black-vs-gray-dark-mode/).

**Comment by maniac103** [comment] 2020-02-19 13:34
Indeed, what @smichel17 said is also my opinion. Thus this is a dupe of #882 and #437.

**Closed by maniac103** 2020-02-19 13:34 UTC
