### ISSUE TITLE
Support GitHub reactions (thumbs up/down, etc)

### ISSUE THREAD

**Issue by mmoayyed** [slapperwan/gh4a#639] opened 2017-06-18 19:08 UTC
When responding to an issue or pull request, github allows for reactions that are thumbs up or thumbs down, hooray, etc. It would be excellent to add support for such reactions into this app as well to reduce "noise" when commenting on an issue, etc.

**Comment by maniac103** [comment] 2017-06-18 19:11
Dupe of #304

**Closed by maniac103** 2017-06-18 19:11 UTC
