### ISSUE TITLE
App crashes when viewing recent wiki updates on Pantech SKY devices

### ISSUE THREAD

**Issue by twse** [slapperwan/gh4a#849] opened 2018-04-28 09:07 UTC
Hi!

When viewing recent wiki updates in any repository, the app crashes on IM-A840SP and many other devices.

Using latest app version on Google Play Store.

**Comment by maniac103** [comment] 2018-04-28 09:47
Dupe of #843.

@slapperwan We need that 4.3.2 :-/

**Closed** 2018-04-28 09:47 UTC
