### ISSUE TITLE
Markdown Table support

### ISSUE THREAD

**Issue by TheJaredWilcurt** [slapperwan/gh4a#301] opened 2016-03-21 23:18 UTC
The README.md for one of my repo's contains a few tables, but they display as inline text in the Android app.

```
Asdf    | Qwer
:--     | :--
**123** | 456
**7**   | 89
```

**Comment by maniac103** [comment] 2016-03-22 05:09
Dupe of #237.

**Closed by maniac103** 2016-03-22 05:09 UTC
