### ISSUE TITLE
Support of GitHub discussions 

### ISSUE THREAD

**Issue by joelchrono12** [slapperwan/gh4a#1121] opened 2021-10-05 19:33 UTC
Yeah, I have recently seen more and more projects making use of discussions for things that are not real issues, almost as a forum of sorts. It would be nice to be able to see them implemented!

Thanks for this amazing app

**Comment by mxmilkiib** [comment] 2021-12-05 00:39
A dupe of #1008 I think

**Comment by maniac103** [comment] 2021-12-05 06:12
Indeed, this is a dupe.

**Closed by maniac103** 2021-12-05 06:12 UTC
