### ISSUE TITLE
add context switch

### ISSUE THREAD

**Issue by ziomau10** [slapperwan/gh4a#514] opened 2017-03-10 14:34 UTC
I am currently invited into several organizations.
On the pc interface i have a button to switch from my repositorie to those on the different organizations.
Is it possible to add such a feature to octodroid?
Thanks and good work.
Regards.
Mau.

**Comment by maniac103** [comment] 2017-03-10 14:44
This is a dupe of #150, right?

**Comment by ziomau10** [comment] 2017-03-10 15:07
Yes, sure ... sorry for the noise ...

**Closed** 2017-03-10 15:07 UTC
