### ISSUE TITLE
Pull request status icons have incorrect colors 

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#441] opened 2017-02-20 15:27 UTC
Not sure if all but they are either fully black or fully white.

**Comment by maniac103** [comment] 2017-02-20 16:46
What status icons do you mean?

**Comment by Tunous** [comment] 2017-02-20 16:47
![screenshot_20170220_140448](https://cloud.githubusercontent.com/assets/5156340/23134318/a03e8888-f794-11e6-8772-5d8e442c8c98.png)
Not sure if other too.

**Comment by maniac103** [comment] 2017-02-20 16:48
For this particular one it's intended: it indicates there's a problem, so it should stand out more than the other icons.

**Comment by Tunous** [comment] 2017-02-20 16:50
If that's the case then I think it would be better to have it colored in red.

**Comment by maniac103** [comment] 2017-02-20 16:58
We could probably try that, but my gut feeling is that it won't look 'right', because it'll be the only colored item there.

**Comment by maniac103** [comment] 2017-03-03 09:32
Closing as it's intended behaviour.

**Closed by maniac103** 2017-03-03 09:32 UTC
