### ISSUE TITLE
Feature request: Scroll down

### ISSUE THREAD

**Issue by osysltd** [slapperwan/gh4a#366] opened 2016-11-11 05:00 UTC
First of all thank you for your existence! Its a pleasure to collaborate by your means, thank you.
A kind of feature request from my side is to 'go down' button on issues and other activity as it makes too long to scroll sometimes, especially on hot discussions.

Anyway thank you for your product!

**Comment by maniac103** [comment] 2016-11-11 05:36
This kinda seems a dupe of #233. Would you agree?

**Comment by osysltd** [comment] 2016-11-11 05:57
Sure, sorry didn't see

**Closed** 2016-11-11 05:57 UTC
