### ISSUE TITLE
NO ENTERPRISE SUPPORT 

### ISSUE THREAD

**Issue by rom4ster** [slapperwan/gh4a#1271] opened 2023-02-17 19:00 UTC
No GitHub Enterprise support makes this app useless

**Comment by sebastien46** [comment] 2023-07-08 10:37
Duplicate of #146

**Closed** 2023-07-09 06:32 UTC

**Comment by erebion** [comment] 2023-12-17 09:14
> No GitHub Enterprise support makes this app useless

Wrong, it's pretty useful to me.

Did you mean to say that you would like to have a feature? lol
