### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by quantenzitrone** [slapperwan/gh4a#1329] opened 2024-06-28 10:38 UTC
### Error stack trace
```
com.squareup.moshi.JsonDataException: Expected an int but was 2147594979 at path $.items[12].pull_request_review_id
	at com.squareup.moshi.JsonUtf8Reader.nextInt(JsonUtf8Reader.java:926)
	at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:196)
	at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:193)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.meisolsson.githubsdk.model.$AutoValue_ReviewComment$MoshiJsonAdapter.fromJson($AutoValue_ReviewComment.java:154)
	at com.meisolsson.githubsdk.model.$AutoValue_ReviewComment$MoshiJsonAdapter.fromJson($AutoValue_ReviewComment.java:31)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:81)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.internal.NonNullJsonAdapter.fromJson(NonNullJsonAdapter.java:43)
	at com.meisolsson.githubsdk.model.AutoValue_Page$MoshiJsonAdapter.fromJson(AutoValue_Page.java:61)
	at com.meisolsson.githubsdk.model.AutoValue_Page$MoshiJsonAdapter.fromJson(AutoValue_Page.java:23)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)
	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at com.tspoon.traceur.ObservableOnAssembly.subscribeActual(ObservableOnAssembly.java:43)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at com.tspoon.traceur.ObservableOnAssembly.subscribeActual(ObservableOnAssembly.java:43)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at com.tspoon.traceur.ObservableOnAssembly.subscribeActual(ObservableOnAssembly.java:43)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at com.tspoon.traceur.ObservableOnAssembly.subscribeActual(ObservableOnAssembly.java:43)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at com.tspoon.traceur.ObservableOnAssembly.subscribeActual(ObservableOnAssembly.java:43)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.drain(ObservableConcatMap.java:223)
	at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.onNext(ObservableConcatMap.java:131)
	at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246)
	at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:569)
	at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitFirst(BehaviorSubject.java:530)
	at io.reactivex.subjects.BehaviorSubject.subscribeActual(BehaviorSubject.java:239)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:53)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at com.tspoon.traceur.ObservableOnAssembly.subscribeActual(ObservableOnAssembly.java:43)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableToListSingle.subscribeActual(ObservableToListSingle.java:58)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleCache.subscribeActual(SingleCache.java:65)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Observable.singleOrError(Observable.java:11667)
	at retrofit2.adapter.rxjava2.RxJava2CallAdapter.adapt(RxJava2CallAdapter.java:79)
	at retrofit2.HttpServiceMethod$CallAdapted.adapt(HttpServiceMethod.java:148)
	at retrofit2.HttpServiceMethod.invoke(HttpServiceMethod.java:132)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:149)
	at java.lang.reflect.Proxy.invoke(Proxy.java:913)
	at $Proxy15.getPullRequestComments(Unknown Source)
	at com.gh4a.fragment.PullRequestConversationFragment.lambda$onCreateDataSingle$4(PullRequestConversationFragment.java:216)
	at com.gh4a.fragment.PullRequestConversationFragment.$r8$lambda$5a2App0_JH2GnP1tLuofSlry7fo(Unknown Source:0)
	at com.gh4a.fragment.PullRequestConversationFragment$$ExternalSyntheticLambda2.getPage(Unknown Source:6)
	at com.gh4a.utils.ApiHelpers$PageIterator.lambda$toSingle$3(ApiHelpers.java:361)
	at com.gh4a.utils.ApiHelpers$PageIterator.$r8$lambda$H0Du61xZUo5PnKYE1PI10bldv20(Unknown Source:0)
	at com.gh4a.utils.ApiHelpers$PageIterator$$ExternalSyntheticLambda6.apply(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.drain(ObservableConcatMap.java:213)
	at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.onNext(ObservableConcatMap.java:131)
	at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246)
	at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:569)
	at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitFirst(BehaviorSubject.java:530)
	at io.reactivex.subjects.BehaviorSubject.subscribeActual(BehaviorSubject.java:239)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:53)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableToListSingle.subscribeActual(ObservableToListSingle.java:58)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleCache.subscribeActual(SingleCache.java:65)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.Single.subscribe(Single.java:3666)
	... 10 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.toObservable(Single.java:4075)
	at com.gh4a.utils.ApiHelpers$PageIterator.lambda$toSingle$3(ApiHelpers.java:362)
	... 42 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Observable.map(Observable.java:9780)
	at com.gh4a.utils.ApiHelpers$PageIterator.evaluateError(ApiHelpers.java:404)
	at com.gh4a.utils.ApiHelpers$PageIterator.$r8$lambda$IOsmdr7R5RjNKZ5Sv0G3KCcF2G0(Unknown Source:0)
	at com.gh4a.utils.ApiHelpers$PageIterator$$ExternalSyntheticLambda0.apply(Unknown Source:0)
	at io.reactivex.Observable.compose(Observable.java:6417)
	at com.gh4a.utils.ApiHelpers$PageIterator.lambda$toSingle$3(ApiHelpers.java:363)
	... 42 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Observable.wrap(Observable.java:4087)
	... 44 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Observable.doOnEach(Observable.java:8138)
	at io.reactivex.Observable.doOnNext(Observable.java:8263)
	at com.gh4a.utils.ApiHelpers$PageIterator.lambda$toSingle$3(ApiHelpers.java:364)
	... 42 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Observable.map(Observable.java:9780)
	at com.gh4a.utils.ApiHelpers$PageIterator.lambda$toSingle$3(ApiHelpers.java:365)
	... 42 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Observable.concatMap(Observable.java:6479)
	at io.reactivex.Observable.concatMap(Observable.java:6442)
	at com.gh4a.utils.ApiHelpers$PageIterator.toSingle(ApiHelpers.java:357)
	at com.gh4a.fragment.PullRequestConversationFragment.onCreateDataSingle(PullRequestConversationFragment.java:216)
	at com.gh4a.fragment.ListDataBaseFragment.loadData(ListDataBaseFragment.java:66)
	at com.gh4a.fragment.ListDataBaseFragment.onViewCreated(ListDataBaseFragment.java:23)
	at com.gh4a.fragment.IssueFragmentBase.onViewCreated(IssueFragmentBase.java:163)
	at com.gh4a.fragment.PullRequestConversationFragment.onViewCreated(PullRequestConversationFragment.java:123)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
	at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:274)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.setOffscreenPageLimit(ViewPager.java:856)
	at com.gh4a.BasePagerActivity.updateTabVisibility(BasePagerActivity.java:143)
	at com.gh4a.BasePagerActivity.invalidatePages(BasePagerActivity.java:61)
	at com.gh4a.BasePagerActivity.invalidateTabs(BasePagerActivity.java:65)
	at com.gh4a.activities.PullRequestActivity.lambda$load$6(PullRequestActivity.java:533)
	at com.gh4a.activities.PullRequestActivity.$r8$lambda$nFWg86hv32nRF6uhTT2bLAk52TI(Unknown Source:0)
	at com.gh4a.activities.PullRequestActivity$$ExternalSyntheticLambda4.accept(Unknown Source:4)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at com.philosophicalhacker.lib.ReactiveLoaders$LoaderSingle$1.onLoadFinished(ReactiveLoaders.java:55)
	at com.philosophicalhacker.lib.RxLoaderCallbacks.onLoadFinished(RxLoaderCallbacks.java:35)
	at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
	at androidx.loader.content.Loader.deliverResult(Loader.java:132)
	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.safeDeliverResult(RxLoaderCallbacks.java:109)
	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.access$000(RxLoaderCallbacks.java:44)
	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader$1.accept(RxLoaderCallbacks.java:80)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Observable.toList(Observable.java:14014)
	at io.reactivex.Observable.toList(Observable.java:13981)
	at com.gh4a.utils.ApiHelpers$PageIterator.toSingle(ApiHelpers.java:367)
	... 46 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.map(Single.java:3045)
	at com.gh4a.utils.ApiHelpers$PageIterator.toSingle(ApiHelpers.java:368)
	... 46 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.map(Single.java:3045)
	at com.gh4a.utils.RxUtils.lambda$sortList$7(RxUtils.java:70)
	at com.gh4a.utils.RxUtils.$r8$lambda$FCbkSHxfFfogzLykFkUxlh_xDFw(Unknown Source:0)
	at com.gh4a.utils.RxUtils$$ExternalSyntheticLambda6.apply(Unknown Source:2)
	at io.reactivex.Single.compose(Single.java:2078)
	at com.gh4a.fragment.PullRequestConversationFragment.onCreateDataSingle(PullRequestConversationFragment.java:217)
	... 45 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.wrap(Single.java:1491)
	... 47 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.cache(Single.java:2097)
	at com.gh4a.fragment.PullRequestConversationFragment.onCreateDataSingle(PullRequestConversationFragment.java:218)
	... 45 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.map(Single.java:3045)
	at com.gh4a.utils.RxUtils.lambda$filter$1(RxUtils.java:37)
	at com.gh4a.utils.RxUtils.$r8$lambda$F5r2vC5ljB9GkPZwSiSwBn3DDfY(Unknown Source:0)
	at com.gh4a.utils.RxUtils$$ExternalSyntheticLambda5.apply(Unknown Source:2)
	at io.reactivex.Single.compose(Single.java:2078)
	at com.gh4a.fragment.PullRequestConversationFragment.onCreateDataSingle(PullRequestConversationFragment.java:291)
	... 45 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.wrap(Single.java:1491)
	... 47 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.map(Single.java:3045)
	at com.gh4a.utils.RxUtils.lambda$mapList$5(RxUtils.java:60)
	at com.gh4a.utils.RxUtils.$r8$lambda$hvD1XKkjf0wJtVRyBqVz9BBpzh8(Unknown Source:0)
	at com.gh4a.utils.RxUtils$$ExternalSyntheticLambda3.apply(Unknown Source:2)
	at io.reactivex.Single.compose(Single.java:2078)
	at com.gh4a.fragment.PullRequestConversationFragment.onCreateDataSingle(PullRequestConversationFragment.java:292)
	... 45 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.wrap(Single.java:1491)
	... 47 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.subscribeOn(Single.java:3740)
	at com.gh4a.fragment.PullRequestConversationFragment.onCreateDataSingle(PullRequestConversationFragment.java:298)
	... 45 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.zipArray(Single.java:1988)
	at io.reactivex.Single.zip(Single.java:1653)
	at com.gh4a.fragment.PullRequestConversationFragment.onCreateDataSingle(PullRequestConversationFragment.java:294)
	... 45 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.subscribeOn(Single.java:3740)
	at com.gh4a.utils.RxUtils.doInBackground(RxUtils.java:89)
	at com.gh4a.BaseActivity$$ExternalSyntheticLambda9.apply(Unknown Source:0)
	at io.reactivex.Single.compose(Single.java:2078)
	at com.gh4a.fragment.LoadingFragmentBase.lambda$makeLoaderSingle$0(LoadingFragmentBase.java:82)
	at com.gh4a.fragment.LoadingFragmentBase.$r8$lambda$ezeDyxD-UcvSxmfC2g4G7aT29vY(Unknown Source:0)
	at com.gh4a.fragment.LoadingFragmentBase$$ExternalSyntheticLambda0.apply(Unknown Source:6)
	at io.reactivex.Single.compose(Single.java:2078)
	at com.gh4a.fragment.ListDataBaseFragment.loadData(ListDataBaseFragment.java:67)
	... 44 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.observeOn(Single.java:3161)
	at com.gh4a.utils.RxUtils.doInBackground(RxUtils.java:90)
	... 51 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.wrap(Single.java:1491)
	... 50 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.subscribeOn(Single.java:3740)
	at com.philosophicalhacker.lib.ReactiveType$Single.subscribeOn(ReactiveType.java:27)
	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onForceLoad(RxLoaderCallbacks.java:76)
	at androidx.loader.content.Loader.forceLoad(Loader.java:347)
	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onStartLoading(RxLoaderCallbacks.java:65)
	at androidx.loader.content.Loader.startLoading(Loader.java:285)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onActive(LoaderManagerImpl.java:77)
	at androidx.lifecycle.LiveData.changeActiveCounter(LiveData.java:390)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:466)
	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:3026)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
	... 38 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.observeOn(Single.java:3161)
	at com.philosophicalhacker.lib.ReactiveType$Single.observeOn(ReactiveType.java:36)
	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onForceLoad(RxLoaderCallbacks.java:77)
	... 53 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.wrap(Single.java:1491)
	at io.reactivex.Single.compose(Single.java:2078)
	at com.gh4a.fragment.LoadingFragmentBase.lambda$makeLoaderSingle$0(LoadingFragmentBase.java:83)
	at com.gh4a.fragment.LoadingFragmentBase.$r8$lambda$ezeDyxD-UcvSxmfC2g4G7aT29vY(Unknown Source:0)
	at com.gh4a.fragment.LoadingFragmentBase$$ExternalSyntheticLambda0.apply(Unknown Source:6)
	at io.reactivex.Single.compose(Single.java:2078)
	at com.gh4a.fragment.ListDataBaseFragment.loadData(ListDataBaseFragment.java:67)
	at com.gh4a.fragment.ListDataBaseFragment.onViewCreated(ListDataBaseFragment.java:23)
	at com.gh4a.fragment.IssueFragmentBase.onViewCreated(IssueFragmentBase.java:163)
	at com.gh4a.fragment.PullRequestConversationFragment.onViewCreated(PullRequestConversationFragment.java:123)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	... 38 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at io.reactivex.Single.wrap(Single.java:1491)
	... 46 more

```

i hope this helps

**Comment by maniac103** [comment] 2024-06-30 12:39
Dupe of #1332

**Closed by maniac103** 2024-06-30 12:39 UTC
