### ISSUE TITLE
Save comment draft

### ISSUE THREAD

**Issue by StefanBrand** [slapperwan/gh4a#815] opened 2018-02-10 16:12 UTC
(or at least display a confirm dialogue if I accidentally try to discard an unsaved issue comment...)

I just typed an issue comment three times because I once clicked the back button and once pressed the pencil button instead of the send button.

Octodroid should save issue comments or at least warn me if I want to discard an unsaved comment.

**Comment by maniac103** [comment] 2018-02-10 18:06
Dupe of #358.

**Closed by maniac103** 2018-02-10 18:07 UTC

**Comment by StefanBrand** [comment] 2018-02-10 23:12
Sorry for the duplicate, the "About" link in the app settings directly leads to a window for a new issue. I couldn't search for existing issues... 😊
-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

Am 10. Februar 2018 19:07:03 MEZ schrieb maniac103 <notifications@github.com>:
>Closed #815.

**Comment by maniac103** [comment] 2018-02-11 09:52
No problem at all, just need to keep the issue list clean :-)
