### ISSUE TITLE
Opening a Github link doesn't work when you're already viewing a page

### ISSUE THREAD

**Issue by yephny** [slapperwan/gh4a#1163] opened 2021-12-28 06:50 UTC
I was checking out the releases section of some software, then I went back to my browser without closing OctoDroid and clicked on a Github link to the issues page of a different repository, but OctoDroid stayed on the same releases page. This happened until I hit the back button (system back, not the in-app back button) a few times and tried again.

**Comment by maniac103** [comment] 2021-12-28 07:07
This sounds like a dupe of #1145?

**Comment by yephny** [comment] 2021-12-28 08:24
That seems to be it, forgot to check closed issues as well. I'll be waiting for the release that includes the fix to test it, thanks.

**Closed** 2021-12-28 08:24 UTC
