### ISSUE TITLE
How to see Pinned issues?

### ISSUE THREAD

**Issue by PrSunflower** [slapperwan/gh4a#1029] opened 2020-09-02 08:02 UTC
Hi, thanks a lot for the OctoDroid app!

When browsing a repo and going to the issues I cannot see issues that were pinned by the owner. Is there a way to see Pinned issues in OctoDroid?

[Example here](https://github.com/zhanghai/MaterialFiles/issues) in OctoDroid I cannot see the "Hall Of Shame" issue.

**Comment by maniac103** [comment] 2020-09-02 16:55
It's there, it's just not pinned, but listed in the middle of the output. As far as I can tell, GitHub's API doesn't support pinned issues (neither by supporting searching for issues in pinned state, nor by explicitly querying pinned issues).

**Comment by PrSunflower** [comment] 2020-09-03 07:21
Ok thank you for the answer. I guess we'll just have to wait then, thanks!

**Comment by PrSunflower** [comment] 2021-03-10 11:54
Hello, hope you are well.

Concerning issues that need API support, do we keep them open? Because like... they're not really an "issue", a problem with the app but rather a missing feature in the platform that supports it.

I wouldn't mind if we closed this issue 🙂

**Comment by maniac103** [comment] 2021-11-27 11:13
We can close, since it's a dupe of #602 anyway ;-)

**Closed by maniac103** 2021-11-27 11:13 UTC
Labels: needs-api-support
