### ISSUE TITLE
Want an update in app

### ISSUE THREAD

**Issue by vivonk** [slapperwan/gh4a#650] opened 2017-07-22 12:21 UTC
If I will able to edit my repositories then it will be great. Please reply if you really thought , it is good.
Allow me to fork this change if you have a git repository.

**Comment by Tunous** [comment] 2017-08-08 18:22
I think that this is a duplicate of #270.

**Closed by Tunous** 2017-08-08 18:22 UTC

**Comment by vivonk** [comment] 2017-09-06 12:54
Sorry, but I did not check previously
