### ISSUE TITLE
Tables are not showing correctly

### ISSUE THREAD

**Issue by tarequemdhanif** [slapperwan/gh4a#814] opened 2018-02-05 18:56 UTC
Tables of markdown files are not showed correctly.

![img_20180205_215620](https://user-images.githubusercontent.com/18123729/35823115-7463fe7a-0abf-11e8-96b3-ca72e977fe26.jpg)

**Comment by maniac103** [comment] 2018-02-05 19:00
Dupe of #237.

**Closed by maniac103** 2018-02-05 19:01 UTC
