### ISSUE TITLE
Theme - custom color selection

### ISSUE THREAD

**Issue by aha999** [slapperwan/gh4a#1037] opened 2020-09-13 11:07 UTC
Add the option to select the theme, based on the colors you select, currently green, i would like to change to blue, and the gray menu part to dark blue for example...

Theme - Custom - Accent color...

I would like to set my theme to look like FastHub libre's premium theme.

**Comment by maniac103** [comment] 2020-09-13 11:19
Dupe of #936

**Closed by maniac103** 2020-09-13 11:19 UTC
