### ISSUE TITLE
counters issue in "About" tabs

### ISSUE THREAD

**Issue by giom-l** [slapperwan/gh4a#886] opened 2019-04-08 11:01 UTC
Octodriod v4.4.0
OS version : Android 8.1.0

There seems to be a problem with the counters of stars, followers, gist... that we can find in "about" tabs (counters on repositories list are ok)

When counters equals 0 on github, Octodroid set them at 1
For a fresh new project : issue, PR, fork, stars & watcher are at 1

I tried to star one of my projects : counter is correctly updated in repositories list but it stays at 1 in "about" tab (and this time, it is correct).

I saw this issue on directory "about" & user "about" tabs.

**Comment by KaKi87** [comment] 2020-06-26 19:53
up

**Comment by smichel17** [comment] 2020-06-26 21:02
Please don't bump. Think about how many people will receive a notification/email. Unless you have something new to add, a thumbs up on the issue is usually enough.

**Comment by KaKi87** [comment] 2020-06-26 21:16
Well, this issue is more than a year old and it shouldn't take so long to fix, that's why I bumbed it.

**Comment by smichel17** [comment] 2020-06-27 03:10
It was rude. Please don't do it again. This will be my last reply on the topic.

**Comment by maniac103** [comment] 2020-06-27 05:35
> it shouldn't take so long to fix

Well, telling me exact reproduction steps would probably help fixing it more than plain bumping. I don't seem to see this issue myself:

![Screenshot_20200626-220156_OctoDroid](https://user-images.githubusercontent.com/781373/85915515-84007500-b848-11ea-877b-86b498305b67.png)

The 1 watcher in the screenshot is correct (myself), all other numbers are correctly at 0.

**Comment by KaKi87** [comment] 2020-06-27 10:03
https://github.com/RafaelDeJongh/h5ai-dark-theme/issues

![image](https://user-images.githubusercontent.com/21284089/85919699-09e2e700-b86e-11ea-877d-a1887d3e0296.png)

![image](https://user-images.githubusercontent.com/21284089/85919716-3991ef00-b86e-11ea-8e70-78fd84917be4.png)

**Comment by maniac103** [comment] 2020-06-27 10:31
Something is odd...

![Screenshot_20200627-123106_OctoDroid](https://user-images.githubusercontent.com/781373/85920214-2a14a500-b872-11ea-841d-efe4059547cf.png)

**Comment by maniac103** [comment] 2020-06-27 10:51
In any case, issue count is reported as 'issue count as reported by GH repository API' minus 'number of PRs as determined by the result count of the issue search "is:pr is:open" for the respective repo'. So in your case, as PR count is correct, it means GH API must have reported issue count as 2 for whatever reason.

**Comment by KaKi87** [comment] 2020-06-27 14:23
Here is another one :

https://github.com/KaKi87/darkreader

![image](https://user-images.githubusercontent.com/21284089/85924390-4d4f4c80-b892-11ea-83c2-2bceb7e5ebf0.png)

![image](https://user-images.githubusercontent.com/21284089/85924410-6fe16580-b892-11ea-8101-f51a14050f7c.png)

**Comment by maniac103** [comment] 2020-06-27 14:41
![Screenshot_20200627-164029_OctoDroid](https://user-images.githubusercontent.com/781373/85924829-ff881380-b894-11ea-9f85-c2f68349438a.png)

I'm really not sure what's going on here... you're on 4.6.1, right?

**Comment by maniac103** [comment] 2020-06-27 14:42
![Screenshot_20200627-164029_OctoDroid](https://user-images.githubusercontent.com/781373/85924829-ff881380-b894-11ea-9f85-c2f68349438a.png)

I'm really not sure what's going on here... you're on 4.6.1, right?

**Comment by maniac103** [comment] 2020-06-27 14:43
![Screenshot_20200627-164029_OctoDroid](https://user-images.githubusercontent.com/781373/85924829-ff881380-b894-11ea-9f85-c2f68349438a.png)

I'm really not sure what's going on here... you're on 4.6.1, right?

**Comment by KaKi87** [comment] 2020-06-27 16:46
Yes.

![image](https://user-images.githubusercontent.com/21284089/85927456-7548ab00-b8a6-11ea-8266-18059fe0d551.png)

**Comment by KaKi87** [comment] 2020-07-06 10:17
![image](https://user-images.githubusercontent.com/21284089/86582716-5e7b1600-bf82-11ea-976c-a7b906f546c3.png)

I'm not sure if it is linked but, besides this private organization's member and repo count is false, I can't access the repos themselves either, despite I'm a member and can access these from github.com

**Comment by maniac103** [comment] 2020-07-06 10:43
> I can't access the repos themselves either, despite I'm a member and can access these from github.com

Need to request org access under GH settings -> Applications -> Authorized OAuth apps -> Octodroid?

**Comment by KaKi87** [comment] 2020-07-06 10:53
> By requesting this approval, you are asking owners of the NearPlay organization to allow this application to access private organization data and modify public organization data.

😂

**Comment by maniac103** [comment] 2020-07-06 11:01
Well, yeah, Octodroid needs write access to those private repos, e.g. for submitting issues...org data itself is treated read only, since Octodroid only requests `read:org` scope.

**Comment by KaKi87** [comment] 2020-07-06 11:11
This request thing of GitHub seems ridiculous.
Why should I have to ask someone else's permission to use an unofficial app to browse git repositories ?
Besides, if I was using an app which works as a scraper and not an API client, it wouldn't even know, so this is not a protection lol
(PS : I know it's not on you, I won't digress any more, I promise).

**Comment by maniac103** [comment] 2020-07-06 16:45
> This request thing of GitHub seems ridiculous.
> Why should I have to ask someone else's permission to use an unofficial app to browse git repositories ?

What's even more funny is that approval is even needed for querying whether or not the authorized user is part of a given org or not -> #934 :-/

**Comment by Fs00** [comment] 2021-11-27 18:44
I have encountered this issue too sometimes, and I believe it has to do with some caching misbehavior.
I was able to reproduce it in a test repository doing the following steps:
- open an issue in the repo (let's assume is the only one)
- visit the repository "About" tab in the app. "1 issue" should be displayed.
- close the issue on another device. Now the GH web UI displays "0 issues".
- leave the repo screen in the app (you can even fully close it) and then return back to it.
The app will still display "1 issue" instead of "0 issues".
**Force refreshing** the screen updates the counter to its correct value ("0 issues").

Wondering whether it's a GitHub API fault or a bug on our side. In the worst case those API calls could always skip the cache @maniac103.

**Comment by maniac103** [comment] 2021-11-27 18:52
If it's caching, we'd need to check ETag responses for either the repository request (in RepositoryActivity) or the PR count (in RepositoryFragment). If the same ETag is returned both before and after the issue count change, that would explain things...

**Comment by KaKi87** [comment] 2022-02-20 18:11
Hello, any news on this ? Thanks

**Comment by RoinujNosde** [comment] 2022-04-13 13:31
I can reproduce it by creating a new repo:
- https://github.com/RoinujNosde/Test
- https://github.com/RoinujNosde/SimpleClansReloaded

**Comment by Fs00** [comment] 2022-07-24 11:31
I've taken a deeper look at this and I've found out that:
- the PR count request does not have an ETag and therefore is never cached
- the repository request **returns the same ETag** regardless of the value of the `open_issues_count` field

So I think we have a few options here:
1. always ignore the cache for the repository request
2. report the issue to GH and see whether they're interested in fixing it
3. make a dedicated request to the search API to get the open issues count as we do with the open PRs one (which will never be cached)

I'd go with option 3 since it makes the behavior more consistent with how we retrieve the open PRs count, and makes us less dependent from GH caching behavior.
WDYT @maniac103?

**Comment by maniac103** [comment] 2022-07-24 13:30
IMHO option 2 should be done in any case, since the same ETag being returned for different data clearly is wrong.
Besides that, I favor option 1 over option 3: the repository response likely is smaller than the search one, and if they messed up ETag generation for this field, who knows what else might be off there.

**Comment by Fs00** [comment] 2022-07-24 18:59
> the repository response likely is smaller than the search one

I've seen that often the opposite is true, it depends on how much the first search result is big. The repository response is always around ~5-6 kB while the PR search response (limited to the first result) ranges between 2.5kB and 10kB.

> if they messed up ETag generation for this field, who knows what else might be off there

That's right, I've noticed that also the `watchers_count` field has the same problem with the ETag.
IMO this is probably the strongest argument in favor of option 1. I'll open a PR in the next few days.

**Comment by maniac103** [comment] 2022-07-24 19:22
> while the PR search response (limited to the first result) ranges between 2.5kB and 10kB.

Combined with an issue search result that would be between 5 and 20 kB ;-)

**Comment by Fs00** [comment] 2022-07-24 19:39
And so option 1 wins 2 to 0 😄

**Closed** 2022-07-28 06:51 UTC
