### ISSUE TITLE
Scrolling releases

### ISSUE THREAD

**Issue by ARoiD** [slapperwan/gh4a#299] opened 2016-03-19 11:48 UTC
Having a hard time loading and scrolling releases

https://github.com/opengapps/arm/releases

**Comment by maniac103** [comment] 2016-03-19 20:16
Please check if the issue is fixed with the above commit and reopen if it isn't.

**Closed** 2016-03-19 20:15 UTC

**Comment by ARoiD** [comment] 2016-03-19 22:17
Opens but entering one of the releases scrolling is stuttering

@maniac103

**Comment by maniac103** [comment] 2016-03-20 06:18
Please define 'stuttering'. You mean you can't fling the download list?

**Comment by ARoiD** [comment] 2016-03-20 12:41
Yes exactly when I try to fling inside one of the release listing it doesn't scroll smoothly like it does when you enter the main releases

**Comment by maniac103** [comment] 2016-03-21 09:16
Should be fixed with the above commit.

**Comment by ARoiD** [comment] 2016-03-21 22:38
Sure did thanks
