### ISSUE TITLE
App crashing when starring after opening github in another app

### ISSUE THREAD

**Issue by UltraBlackLinux** [slapperwan/gh4a#993] opened 2020-06-25 20:33 UTC
Hello,
Im having some trouble with the app:
1.    Open an App that has a github Source Link in it
2.    Open the link, so that the original app is now kinda the Github app
3.    Do sth, e.g. starring, trying to create an Issue,...
4.    Watch the app crash

Really like the app, continue working on it :)

**Comment by maniac103** [comment] 2020-06-26 04:20
Can you please give exact reproduction steps for the crash(es)?

**Comment by UltraBlackLinux** [comment] 2020-06-27 07:48
1. Open an App that has a github Source Link in it
2. Open the link, so that the original app is now kinda the Github app
3. Do sth, e.g. starring, trying to create an Issue,...
4. Watch the app crash

**Comment by maniac103** [comment] 2020-06-27 08:35
That's not exactly exact ;-) What repo do you visit, and what exactly is 'do sth"?

**Comment by maniac103** [comment] 2020-06-27 08:35
(I suspect this is a dupe of #988 and #992)

**Closed** 2020-07-15 11:52 UTC
