### ISSUE TITLE
Rendering of tables

### ISSUE THREAD

**Issue by PatrickvL** [slapperwan/gh4a#652] opened 2017-07-28 05:57 UTC
OctoDroid doesn't render tables.
Github offers syntax to show tables, as described here : https://help.github.com/articles/organizing-information-with-tables/

Here an example use : https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/222

For this issue, extend OctoDroid so tables are rendered correctly.

**Comment by Tunous** [comment] 2017-07-28 08:16
Duplicate of #237

**Closed** 2017-07-28 08:17 UTC
