### ISSUE TITLE
New issue "+" button

### ISSUE THREAD

**Issue by ildar** [slapperwan/gh4a#732] opened 2017-09-16 06:35 UTC
When a user opens Issues view, he can see the "+" button in the right bottom corner. But when he scrolls issues the button disappears and don't come back.

**Comment by maniac103** [comment] 2017-09-16 06:49
Dupe of #711 (and already fixed, see #673)

**Closed** 2017-09-16 06:49 UTC

**Comment by Tunous** [comment] 2017-09-16 08:00
@slapperwan it would be a good idea to release a bug fix update.

**Comment by maniac103** [comment] 2017-09-16 18:29
> @slapperwan it would be a good idea to release a bug fix update.

+1, but please wait until Monday; I got another fix to make.

**Comment by slapperwan** [comment] 2017-09-16 19:25
Ok sure, let me know once done.

**Comment by maniac103** [comment] 2017-09-19 14:45
@slapperwan Done :)

**Comment by slapperwan** [comment] 2017-09-20 02:04
Thank you, I will release it coming 1-2 days.
