### ISSUE TITLE
trending repos not working

### ISSUE THREAD

**Issue by veeragoni** [slapperwan/gh4a#519] opened 2017-03-12 02:22 UTC
Could you please fix it

**Comment by Tunous** [comment] 2017-03-12 12:04
Duplicate of https://github.com/slapperwan/gh4a/issues/386

**Comment by maniac103** [comment] 2017-03-12 13:45
https://github.com/slapperwan/gh4a/commit/e6912c826e541223725dbfabbc21c89a4615510e should fix this for the foreseeable future.

**Closed by maniac103** 2017-03-12 13:45 UTC
