### ISSUE TITLE
Support for collapsible sections in Markdown

### ISSUE THREAD

**Issue by aha999** [slapperwan/gh4a#1075] opened 2021-05-12 15:55 UTC
Currently, OCtodroid doesn't have support for collapsible lists in github. The readme's that have it look bad in octodroid. Some other client apps support it, so it's much better if octodroid did too.

#### This is a collapsible section (click to expand):
<details>
  <summary>Click to expand!</summary>
  
  ## Heading
  1. A numbered
  2. list
     * With some
     * Sub bullets
</details>

[How to add a collapsible section in markdown.](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab)

**Comment by Fs00** [comment] 2022-01-09 10:58
Duplicate of #581

**Closed** 2022-01-09 11:03 UTC
