### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by poutros** [slapperwan/gh4a#355] opened 2016-10-09 19:38 UTC

**Comment by maniac103** [comment] 2016-10-09 20:08
'Support' as in...?

**Comment by poutros** [comment] 2016-10-10 00:37
Support for the reaction emojis that github added.

**Comment by maniac103** [comment] 2016-10-10 04:03
I see. This is a dupe of #304 then.

**Closed by maniac103** 2016-10-10 04:03 UTC

**Comment by poutros** [comment] 2016-10-10 09:18
Oh, I searched for emoji. That's why I didn't find any issue related to it.
