### ISSUE TITLE
Cannot select issue templates

### ISSUE THREAD

**Issue by Etim-Orb** [slapperwan/gh4a#1187] opened 2022-03-13 21:31 UTC
I have noticed that I do not get an issue template popup when making one. I have checked this with multiple projects that have these temeplates. Perhaps there's a change on GitHub's end.

**Comment by Fs00** [comment] 2022-03-14 07:50
Which is the repository that exhibits this problem? I've tested on a few repos and issue templates still work.
I suspect that you're experiencing #1159.

**Comment by Etim-Orb** [comment] 2022-03-14 16:52
@Fs00 Bromite and Newpipe.

**Comment by Fs00** [comment] 2022-03-14 17:09
Just checked and both repos use the new issue form templates, which are not supported by OctoDroid.
Duplicate of #1159.

**Closed** 2022-03-14 17:18 UTC
