### ISSUE TITLE
ApiRequestException (404)

### ISSUE THREAD

**Issue by ildar** [slapperwan/gh4a#845] opened 2018-04-17 08:56 UTC
Trying https://github.com/adafruit I see a strange error: 404

> Tue, 17 Apr 2018 14:51:06 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : Loading data failed
> Tue, 17 Apr 2018 14:51:06 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : com.gh4a.ApiRequestException: Not Found (404)
> Tue, 17 Apr 2018 14:51:06 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at com.gh4a.utils.ApiHelpers.throwOnFailure(ApiHelpers.java:172)
> Tue, 17 Apr 2018 14:51:06 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at com.gh4a.fragment.PagedDataBaseFragment$$Lambda$6.apply(Unknown Source)
> Tue, 17 Apr 2018 14:51:06 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:56)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:63)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:111)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:47)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at io.reactivex.Observable.subscribe(Observable.java:10700)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at io.reactivex.Single.subscribe(Single.java:2692)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:33)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at io.reactivex.Single.subscribe(Single.java:2692)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:33)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at io.reactivex.Single.subscribe(Single.java:2692)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at io.reactivex.Scheduler$1.run(Scheduler.java:138)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> Tue, 17 Apr 2018 14:51:08 +0600: 04-17 14:51:04.269  1460  1460 D Gh4a    : 	at java.lang.Thread.run(Thread.java:818)

**Comment by maniac103** [comment] 2018-04-17 15:40
Looks like this has the same root cause as #830 , which is already fixed in master.

**Closed by maniac103** 2018-04-17 15:40 UTC

**Comment by ildar** [comment] 2018-04-18 03:09
I see!
Smells like a good time for butfix release 😉

**Comment by ildar** [comment] 2018-04-18 04:45
ah! I see. Actually if desired and if it's ok for slapperwan, you can just
push a tag. Then it'll be enough for the new version build with F-Droid.
