### ISSUE TITLE
Show notifications

### ISSUE THREAD

**Issue by sbrl** [slapperwan/gh4a#272] opened 2015-10-12 07:31 UTC
It would be awesome if this app showed me my GitHub notifications.

**Comment by TheKing42** [comment] 2016-01-31 16:10
:+1:

**Comment by JasperWeiss** [comment] 2016-02-07 09:00
I'd like that too actually.

**Comment by fountaingeyser** [comment] 2016-02-29 21:44
:+1:

**Comment by maniac103** [comment] 2016-03-13 09:23
Dupe of #175.

**Closed by maniac103** 2016-03-13 09:23 UTC
