### ISSUE TITLE
Incorrect text is displayed in the button present in the My issues activity  

### ISSUE THREAD

**Issue by AbhilashG97** [slapperwan/gh4a#529] opened 2017-03-17 10:21 UTC
**Summary:**

Incorrect text is displayed in the button present in the My issues activity. When we tap on the "SHOW CLOSED" button on the top right  in the toolbar, we get to see a new activity which displays closed issues. But the the text inside button doesn't change to "SHOW OPEN" in the closed issues activity. It doesn't make sense to display the text inside the button as "SHOW CLOSED", as the user would already be viewing closed issues. 

**Steps to reproduce:**

Step 1) Tap on the "My issues" in the navigation drawer.
Step 2) Tap on "SHOW CLOSED".

**Expected Behaviour:** 

The text inside the button should display "SHOW OPEN", as tapping on the button displays open issues.

**Observed Behaviour:**

The text inside the button displays "SHOW CLOSED" instead of displaying "SHOW OPEN".

**Device and Android Version:**

Device : Motorola Moto G 1st Generation [XT1033] [Falcon]
ROM : CyanogenMod 13.0 Snapshot build

**Screenshots:**

![screenshot_20170317-154738](https://cloud.githubusercontent.com/assets/20839661/24038830/20cf0afc-0b29-11e7-9985-429162530d5b.png)

![screenshot_20170317-154731](https://cloud.githubusercontent.com/assets/20839661/24038829/20a77816-0b29-11e7-8689-af75dfde587b.png)

**Comment by maniac103** [comment] 2017-03-17 11:21
Dupe of #360, #510.

**Closed by maniac103** 2017-03-17 11:21 UTC
