### ISSUE TITLE
Crash when opening PR

### ISSUE THREAD

**Issue by mueller-ma** [slapperwan/gh4a#1355] opened 2024-07-08 17:07 UTC
When I open https://github.com/openhab/openhab-android/pull/3723, the first post is loaded, then the app crashes. I had to use adb to get the stack trace as the built-in crash reporter (that I got in #1335) didn't show up.

4.6.11 via F-Droid.

````
2024-07-08 19:05:16.868 19621-19621 AndroidRuntime          com.gh4a                             E  FATAL EXCEPTION: main
                                                                                                    Process: com.gh4a, PID: 19621
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.gh4a.model.TimelineItem$TimelineReview.addComment(com.meisolsson.githubsdk.model.ReviewComment, com.meisolsson.githubsdk.model.GitHubFile, boolean)' on a null object reference
                                                                                                    	at com.gh4a.fragment.PullRequestConversationFragment.lambda$onCreateDataSingle$9(PullRequestConversationFragment.java:271)
                                                                                                    	at com.gh4a.fragment.PullRequestConversationFragment$$ExternalSyntheticLambda12.apply(D8$$SyntheticClass:0)
                                                                                                    	at io.reactivex.internal.functions.Functions$Array3Func.apply(Functions.java:546)
                                                                                                    	at io.reactivex.internal.functions.Functions$Array3Func.apply(Functions.java:533)
                                                                                                    	at io.reactivex.internal.operators.single.SingleZipArray$ZipCoordinator.innerSuccess(SingleZipArray.java:112)
                                                                                                    	at io.reactivex.internal.operators.single.SingleZipArray$ZipSingleObserver.onSuccess(SingleZipArray.java:170)
                                                                                                    	at com.tspoon.traceur.SingleOnAssembly$OnAssemblySingleObserver.onSuccess(SingleOnAssembly.java:70)
                                                                                                    	at io.reactivex.internal.operators.single.SingleCache.onSuccess(SingleCache.java:134)
                                                                                                    	at com.tspoon.traceur.SingleOnAssembly$OnAssemblySingleObserver.onSuccess(SingleOnAssembly.java:70)
                                                                                                    	at com.tspoon.traceur.SingleOnAssembly$OnAssemblySingleObserver.onSuccess(SingleOnAssembly.java:70)
                                                                                                    	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
                                                                                                    	at com.tspoon.traceur.SingleOnAssembly$OnAssemblySingleObserver.onSuccess(SingleOnAssembly.java:70)
                                                                                                    	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
                                                                                                    	at com.tspoon.traceur.SingleOnAssembly$OnAssemblySingleObserver.onSuccess(SingleOnAssembly.java:70)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableToListSingle$ToListObserver.onComplete(ObservableToListSingle.java:111)
                                                                                                    	at io.reactivex.internal.observers.BasicFuseableObserver.onComplete(BasicFuseableObserver.java:119)
                                                                                                    	at io.reactivex.observers.SerializedObserver.onComplete(SerializedObserver.java:179)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.drain(ObservableConcatMap.java:205)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver.onComplete(ObservableConcatMap.java:151)
                                                                                                    	at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:239)
                                                                                                    	at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:569)
                                                                                                    	at io.reactivex.internal.util.AppendOnlyLinkedArrayList.forEachWhile(AppendOnlyLinkedArrayList.java:93)
                                                                                                    	at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitLoop(BehaviorSubject.java:587)
                                                                                                    	at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitFirst(BehaviorSubject.java:534)
                                                                                                    	at io.reactivex.subjects.BehaviorSubject.subscribeActual(BehaviorSubject.java:239)
                                                                                                    	at io.reactivex.Observable.subscribe(Observable.java:12284)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:53)
                                                                                                    	at io.reactivex.Observable.subscribe(Observable.java:12284)
                                                                                                    	at com.tspoon.traceur.ObservableOnAssembly.subscribeActual(ObservableOnAssembly.java:43)
                                                                                                    	at io.reactivex.Observable.subscribe(Observable.java:12284)
                                                                                                    	at io.reactivex.internal.operators.observable.ObservableToListSingle.subscribeActual(ObservableToListSingle.java:58)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
2024-07-08 19:05:16.869 19621-19621 AndroidRuntime          com.gh4a                             E  	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at io.reactivex.internal.operators.single.SingleCache.subscribeActual(SingleCache.java:65)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3666)
                                                                                                    	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
                                                                                                    	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
                                                                                                    	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                                                                    	at java.lang.Thread.getStackTrace(Thread.java:1841)
                                                                                                    	at io.reactivex.Single.zipArray(Single.java:1988)
                                                                                                    	at io.reactivex.Single.zip(Single.java:1608)
                                                                                                    	at com.gh4a.fragment.PullRequestConversationFragment.onCreateDataSingle(PullRequestConversationFragment.java:242)
                                                                                                    	at com.gh4a.fragment.ListDataBaseFragment.loadData(ListDataBaseFragment.java:66)
                                                                                                    	at com.gh4a.fragment.ListDataBaseFragment.onViewCreated(ListDataBaseFragment.java:23)
                                                                                                    	at com.gh4a.fragment.IssueFragmentBase.onViewCreated(IssueFragmentBase.java:163)
                                                                                                    	at com.gh4a.fragment.PullRequestConversationFragment.onViewCreated(PullRequestConversationFragment.java:122)
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
                                                                                                    	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1729)
                                                                                                    	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
                                                                                                    	at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:274)
                                                                                                    	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
                                                                                                    	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
                                                                                                    	at androidx.viewpager.widget.ViewPager.setOffscreenPageLimit(ViewPager.java:856)
                                                                                                    	at com.gh4a.BasePagerActivity.updateTabVisibility(BasePagerActivity.java:141)
                                                                                                    	at com.gh4a.BasePagerActivity.invalidatePages(BasePagerActivity.java:59)
                                                                                                    	at com.gh4a.BasePagerActivity.invalidateTabs(BasePagerActivity.java:63)
2024-07-08 19:05:16.869 19621-19621 AndroidRuntime          com.gh4a                             E  	at com.gh4a.activities.PullRequestActivity.lambda$load$6$com-gh4a-activities-PullRequestActivity(PullRequestActivity.java:531)
                                                                                                    	at com.gh4a.activities.PullRequestActivity$$ExternalSyntheticLambda4.accept(D8$$SyntheticClass:0)
                                                                                                    	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
                                                                                                    	at com.philosophicalhacker.lib.ReactiveLoaders$LoaderSingle$1.onLoadFinished(ReactiveLoaders.java:55)
                                                                                                    	at com.philosophicalhacker.lib.RxLoaderCallbacks.onLoadFinished(RxLoaderCallbacks.java:35)
                                                                                                    	at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
                                                                                                    	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
                                                                                                    	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
                                                                                                    	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
                                                                                                    	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
                                                                                                    	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
                                                                                                    	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
                                                                                                    	at androidx.loader.content.Loader.deliverResult(Loader.java:132)
                                                                                                    	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.safeDeliverResult(RxLoaderCallbacks.java:109)
                                                                                                    	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.access$000(RxLoaderCallbacks.java:44)
                                                                                                    	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader$1.accept(RxLoaderCallbacks.java:80)
                                                                                                    	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
                                                                                                    	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
                                                                                                    	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7924)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
                                                                                                    	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                                                                    	at java.lang.Thread.getStackTrace(Thread.java:1841)
                                                                                                    	at io.reactivex.Single.map(Single.java:3045)
                                                                                                    	at com.gh4a.utils.RxUtils.lambda$filter$1(RxUtils.java:37)
                                                                                                    	at com.gh4a.utils.RxUtils$$ExternalSyntheticLambda12.apply(D8$$SyntheticClass:0)
                                                                                                    	at io.reactivex.Single.compose(Single.java:2078)
                                                                                                    	at com.gh4a.fragment.PullRequestConversationFragment.onCreateDataSingle(PullRequestConversationFragment.java:280)
                                                                                                    	... 45 more
                                                                                                    Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
                                                                                                    	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                                                                    	at java.lang.Thread.getStackTrace(Thread.java:1841)
                                                                                                    	at io.reactivex.Single.wrap(Single.java:1491)
                                                                                                    	... 47 more
                                                                                                    Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
                                                                                                    	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                                                                    	at java.lang.Thread.getStackTrace(Thread.java:1841)
                                                                                                    	at io.reactivex.Single.subscribeOn(Single.java:3740)
                                                                                                    	at com.gh4a.fragment.PullRequestConversationFragment.onCreateDataSingle(PullRequestConversationFragment.java:296)
                                                                                                    	... 45 more
                                                                                                    Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
                                                                                                    	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                                                                    	at java.lang.Thread.getStackTrace(Thread.java:1841)
                                                                                                    	at io.reactivex.Single.zipArray(Single.java:1988)
                                                                                                    	at io.reactivex.Single.zip(Single.java:1653)
                                                                                                    	at com.gh4a.fragment.PullRequestConversationFragment.onCreateDataSingle(PullRequestConversationFragment.java:293)
                                                                                                    	... 45 more
                                                                                                    Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
2024-07-08 19:05:16.869 19621-19621 AndroidRuntime          com.gh4a                             E  	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                                                                    	at java.lang.Thread.getStackTrace(Thread.java:1841)
                                                                                                    	at io.reactivex.Single.subscribeOn(Single.java:3740)
                                                                                                    	at com.gh4a.utils.RxUtils.doInBackground(RxUtils.java:89)
                                                                                                    	at com.gh4a.BaseActivity$$ExternalSyntheticLambda2.apply(D8$$SyntheticClass:0)
                                                                                                    	at io.reactivex.Single.compose(Single.java:2078)
                                                                                                    	at com.gh4a.fragment.LoadingFragmentBase.lambda$makeLoaderSingle$0$com-gh4a-fragment-LoadingFragmentBase(LoadingFragmentBase.java:82)
                                                                                                    	at com.gh4a.fragment.LoadingFragmentBase$$ExternalSyntheticLambda0.apply(D8$$SyntheticClass:0)
                                                                                                    	at io.reactivex.Single.compose(Single.java:2078)
                                                                                                    	at com.gh4a.fragment.ListDataBaseFragment.loadData(ListDataBaseFragment.java:67)
                                                                                                    	... 44 more
                                                                                                    Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
                                                                                                    	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                                                                    	at java.lang.Thread.getStackTrace(Thread.java:1841)
                                                                                                    	at io.reactivex.Single.observeOn(Single.java:3161)
                                                                                                    	at com.gh4a.utils.RxUtils.doInBackground(RxUtils.java:90)
                                                                                                    	... 50 more
                                                                                                    Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
                                                                                                    	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                                                                    	at java.lang.Thread.getStackTrace(Thread.java:1841)
                                                                                                    	at io.reactivex.Single.wrap(Single.java:1491)
                                                                                                    	... 49 more
                                                                                                    Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
                                                                                                    	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                                                                    	at java.lang.Thread.getStackTrace(Thread.java:1841)
                                                                                                    	at io.reactivex.Single.subscribeOn(Single.java:3740)
                                                                                                    	at com.philosophicalhacker.lib.ReactiveType$Single.subscribeOn(ReactiveType.java:27)
                                                                                                    	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onForceLoad(RxLoaderCallbacks.java:76)
                                                                                                    	at androidx.loader.content.Loader.forceLoad(Loader.java:347)
                                                                                                    	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onStartLoading(RxLoaderCallbacks.java:65)
                                                                                                    	at androidx.loader.content.Loader.startLoading(Loader.java:285)
                                                                                                    	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onActive(LoaderManagerImpl.java:77)
                                                                                                    	at androidx.lifecycle.LiveData.changeActiveCounter(LiveData.java:405)
                                                                                                    	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:481)
                                                                                                    	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:440)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:251)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)
                                                                                                    	at androidx.fragment.app.Fragment.performStart(Fragment.java:3167)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:588)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
                                                                                                    	... 38 more
                                                                                                    Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
                                                                                                    	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                                                                    	at java.lang.Thread.getStackTrace(Thread.java:1841)
                                                                                                    	at io.reactivex.Single.observeOn(Single.java:3161)
                                                                                                    	at com.philosophicalhacker.lib.ReactiveType$Single.observeOn(ReactiveType.java:36)
                                                                                                    	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onForceLoad(RxLoaderCallbacks.java:77)
                                                                                                    	... 53 more
                                                                                                    Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
                                                                                                    	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                                                                    	at java.lang.Thread.getStackTrace(Thread.java:1841)
                                                                                                    	at io.reactivex.Single.wrap(Single.java:1491)
                                                                                                    	at io.reactivex.Single.compose(Single.java:2078)
                                                                                                    	at com.gh4a.fragment.LoadingFragmentBase.lambda$makeLoaderSingle$0$com-gh4a-fragment-LoadingFragmentBase(LoadingFragmentBase.java:83)
                                                                                                    	at com.gh4a.fragment.LoadingFragmentBase$$ExternalSyntheticLambda0.apply(D8$$SyntheticClass:0)
2024-07-08 19:05:16.869 19621-19621 AndroidRuntime          com.gh4a                             E  	at io.reactivex.Single.compose(Single.java:2078)
                                                                                                    	at com.gh4a.fragment.ListDataBaseFragment.loadData(ListDataBaseFragment.java:67)
                                                                                                    	at com.gh4a.fragment.ListDataBaseFragment.onViewCreated(ListDataBaseFragment.java:23)
                                                                                                    	at com.gh4a.fragment.IssueFragmentBase.onViewCreated(IssueFragmentBase.java:163)
                                                                                                    	at com.gh4a.fragment.PullRequestConversationFragment.onViewCreated(PullRequestConversationFragment.java:122)
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
                                                                                                    	... 38 more
                                                                                                    Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
                                                                                                    	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                                                                    	at java.lang.Thread.getStackTrace(Thread.java:1841)
                                                                                                    	at io.reactivex.Single.wrap(Single.java:1491)
                                                                                                    	... 46 more
````

**Comment by maniac103** [comment] 2024-07-09 07:29
Now I see why I couldn't reproduce it (anymore) ... I had the fix for this locally, but forgot to push :roll_eyes: Will tag a new release with it soon.

**Closed** 2024-07-09 07:28 UTC
