### ISSUE TITLE
Confirm before exiting issue submission

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [slapperwan/gh4a#1095] opened 2021-08-02 12:17 UTC
There are currently no confirmation to prevent accidentally exiting out of an issue edit. Both by the "back UI button" in the app and the native Android back button.

Ties into draft support in #1086

**Comment by maniac103** [comment] 2021-11-27 11:08
Dupe of #358.

**Closed by maniac103** 2021-11-27 11:08 UTC
